version: '2'

services:
    app:
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        links:
            - mysql
        volumes:
            - ".:/var/www/app"
            - "./docker/volumes/app:/var/www/app/var/log"

    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=cent-degres-crm
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - "./docker/volumes/mysql:/var/lib/mysql"

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "8080:80"
        links:
            - php
        volumes:
            - "./docker/volumes/nginx/:/var/log/nginx"
        volumes_from:
            - php

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        links:
            - mysql
        environment:
            - PMA_HOST=mysql

    maildev:
        image: djfarrelly/maildev
        ports:
            - "1080:80"
