version: '2'

services:

    php:
        build:
            context: ./docker/php
        links:
            - mysql
        env_file:
            - .env
        volumes:
            - ".:/var/www"

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "${SERVER_PORT}:80"
        links:
            - php
        volumes:
            - "./docker/volumes/nginx/:/var/log/nginx"
        volumes_from:
            - php

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=StrongPassword
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - "./docker/volumes/mysql:/var/lib/mysql"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PMA_PORT}:80"
        links:
            - mysql
        environment:
            - PMA_HOST=${DB_HOST}

    maildev:
        image: djfarrelly/maildev
        ports:
            - "${MAILDEV_PORT}:80"
